file_format: "1"
id: chonky_trackball_less
name: chonky_trackball_less
type: shield
url: https://gitea.gimmin.com/billy/chonky_trackball
requires: [pro_micro]
features:
  - keys
siblings:
  - chonky_trackball_less_left
  - chonky_trackball_less_right
  - chonky_trackball_less_dongle
